# Generated by Django 5.2 on 2025-08-28 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("board", "0009_alter_board_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imgfile", models.ImageField(blank=True, upload_to="board/%Y/%m/%d")),
                (
                    "board_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_images",
                        to="board.board",
                    ),
                ),
            ],
        ),
    ]
