# Generated by Django 5.2 on 2025-08-17 02:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0002_remove_board_writer_board_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
