# Generated by Django 5.2 on 2025-08-19 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0006_alter_image_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="board_image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="board.board",
            ),
        ),
    ]
